{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring-stack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    {{- include "monitoring-stack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.serviceMonitor.targetAppLabel | default "java-k8s-app-chart" }}
  namespaceSelector:
    matchNames:
      - {{ .Values.serviceMonitor.targetNamespace | default "java-k8s" }}
  endpoints:
    - port: {{ .Values.serviceMonitor.portName | default "http" }}
      path: {{ .Values.serviceMonitor.path | default "/actuator/prometheus" }}
      interval: {{ .Values.serviceMonitor.interval | default "15s" }}
  {{- end }}

